"""Add Phase 5 verification session active workflow fields

Revision ID: 9b3e0150be19
Revises: 9d2d53afcf31
Create Date: 2026-08-18 21:27:50.717976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b3e0150be19'
down_revision: Union[str, None] = '9d2d53afcf31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_sessions', sa.Column('ticket_id', sa.String(length=36), nullable=False))
    op.add_column('verification_sessions', sa.Column('worker_id', sa.String(length=36), nullable=False))
    op.add_column('verification_sessions', sa.Column('challenge_type', sa.String(length=100), nullable=False))
    op.add_column('verification_sessions', sa.Column('challenge_text', sa.String(length=255), nullable=False))
    op.add_column('verification_sessions', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('verification_sessions', 'evidence_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_verification_sessions_status'), 'verification_sessions', ['status'], unique=False)
    op.drop_constraint('verification_sessions_evidence_id_fkey', 'verification_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'verification_sessions', 'tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'verification_sessions', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'verification_sessions', 'ticket_evidence', ['evidence_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verification_sessions', type_='foreignkey')
    op.drop_constraint(None, 'verification_sessions', type_='foreignkey')
    op.drop_constraint(None, 'verification_sessions', type_='foreignkey')
    op.create_foreign_key('verification_sessions_evidence_id_fkey', 'verification_sessions', 'ticket_evidence', ['evidence_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_verification_sessions_status'), table_name='verification_sessions')
    op.alter_column('verification_sessions', 'evidence_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_column('verification_sessions', 'expires_at')
    op.drop_column('verification_sessions', 'challenge_text')
    op.drop_column('verification_sessions', 'challenge_type')
    op.drop_column('verification_sessions', 'worker_id')
    op.drop_column('verification_sessions', 'ticket_id')
    # ### end Alembic commands ###
