"""Add Phase 4 evidence management fields

Revision ID: 9d2d53afcf31
Revises: b4ac2a808410
Create Date: 2026-08-18 21:24:20.828416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2d53afcf31'
down_revision: Union[str, None] = 'b4ac2a808410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_evidence', sa.Column('evidence_type', sa.String(length=50), nullable=False))
    op.add_column('ticket_evidence', sa.Column('source_type', sa.String(length=50), nullable=False))
    op.add_column('ticket_evidence', sa.Column('perceptual_hash', sa.String(length=64), nullable=True))
    op.add_column('ticket_evidence', sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ticket_evidence', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('ticket_evidence', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('ticket_evidence', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('ticket_evidence', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('ticket_evidence', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('ticket_evidence', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('ticket_evidence', sa.Column('verification_session_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_ticket_evidence_evidence_type'), 'ticket_evidence', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_ticket_evidence_perceptual_hash'), 'ticket_evidence', ['perceptual_hash'], unique=False)
    op.create_index(op.f('ix_ticket_evidence_source_type'), 'ticket_evidence', ['source_type'], unique=False)
    op.create_foreign_key(None, 'ticket_evidence', 'verification_sessions', ['verification_session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_evidence', type_='foreignkey')
    op.drop_index(op.f('ix_ticket_evidence_source_type'), table_name='ticket_evidence')
    op.drop_index(op.f('ix_ticket_evidence_perceptual_hash'), table_name='ticket_evidence')
    op.drop_index(op.f('ix_ticket_evidence_evidence_type'), table_name='ticket_evidence')
    op.drop_column('ticket_evidence', 'verification_session_id')
    op.drop_column('ticket_evidence', 'file_size_bytes')
    op.drop_column('ticket_evidence', 'height')
    op.drop_column('ticket_evidence', 'width')
    op.drop_column('ticket_evidence', 'longitude')
    op.drop_column('ticket_evidence', 'latitude')
    op.drop_column('ticket_evidence', 'uploaded_at')
    op.drop_column('ticket_evidence', 'captured_at')
    op.drop_column('ticket_evidence', 'perceptual_hash')
    op.drop_column('ticket_evidence', 'source_type')
    op.drop_column('ticket_evidence', 'evidence_type')
    # ### end Alembic commands ###
