"""Add Phase 3 ticket fields complaint_type latitude longitude

Revision ID: b4ac2a808410
Revises: 585bfb3f5d68
Create Date: 2026-08-18 21:20:58.970264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ac2a808410'
down_revision: Union[str, None] = '585bfb3f5d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('complaint_type', sa.String(length=100), nullable=False))
    op.add_column('tickets', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_index(op.f('ix_tickets_complaint_type'), 'tickets', ['complaint_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_complaint_type'), table_name='tickets')
    op.drop_column('tickets', 'longitude')
    op.drop_column('tickets', 'latitude')
    op.drop_column('tickets', 'complaint_type')
    # ### end Alembic commands ###
